[package]
name = "native_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
procout = "0.1.13"
syn = "2.0.48"
quote = "1.0.35"
proc-macro2 = "1.0.76"
to_snake_case = "0.1.1"
proc-macro-crate = "3.1.0"

[lib]
proc-macro = true